apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: seed-job
  name: seed-job
spec:
  template:
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/tuto-terraform-406010/voting-app-repo/seed-data
        name: seed-job
        env:
        - name: TARGET_HOST
          value: "vote"
        - name: TARGET_PORT
          value: "5000"
      restartPolicy: Never
