apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-deplt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/tuto-terraform-406010/voting-app-repo/vote
        name: vote-container
        ports:
        - containerPort: 5000
          name: vote-port
        livenessProbe:
          httpGet:
            path: /
            port: vote-port
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 2
          initialDelaySeconds: 5
